### PR TITLE
Better error handling and output format

### PR DESCRIPTION
**Pull request by ToonSpin**
Hi @mikepound,

I've used the script to check a number of passwords of mine, and one of my passwords could not be encoded to ASCII, and therefore not hashed, and in turn also not checked. Let's just say it's because there was a character in the password that belongs to a quite exotic character set, and that finding this out was quite hilarious.

Your script does not handle this situation gracefully and I feel that when checking several passwords you don't want the program to stop on the first error it finds, just because a password has a weird character in it.

Also I noticed a small error in the README: when piping output into your script, then using `<` to read in a file does not make sense.

Let me know if there is anything you would like me to improve before merging, I would be happy to do so.

Thanks for putting in the time to make this!

Toon

### CODE REVIEW

**Comment by aditya95sriram** [comment]
Looking at the error handling commit, I feel it's better to just catch `RuntimeError`s explicitly and let the other errors bubble to the top. The `lookup_pwned_api` function raises a `RuntimeError` in case the request didn't go through.

    try:
        ...
    except RuntimeError:
        print(pwd, "could not be checked: ", sys.exc_info()[1])

**Comment by ToonSpin** [comment]
@aditya95sriram, I would do the exact opposite because the error that gets thrown is a `UnicodeEncodeError`, not a `RuntimeError`. Therefore what you are proposing is that passwords that contain characters that cannot be hashed, stop the entire process, which is what happens now and is what this PR is supposed to fix.

Also a `RuntimeError` is for when something goes wrong that is not some other error: surely a `RuntimeError` should bubble to the top, and not an error where it's clear what went wrong and where we know it can't be fixed?

Edit: I see where you are coming from now so I fixed it, please see commit 4a65051b2831c8b4ea5e70b2597bf5e637c3530a.

**Comment by ToonSpin** [comment]
Actually @mikepound why do you convert to ASCII? Why not convert to UTF-8 - ASCII text is also valid UTF-8 text and converting to UTF-8 also solves this issue - also the documentation of the haveibeenpwned API states that passwords are UTF-8 encoded.

**Comment by ToonSpin** [comment]
Perhaps @aditya95sriram's mention of `RuntimeError`s came from the fact that the Python file refers to `RuntimeError`s, but the `encode` method returns different errors that I think are good to catch. I've added commit 4a65051b2831c8b4ea5e70b2597bf5e637c3530a to only catch those, because I do think the reasoning was sound there.

Also I've added commit 320c783a868a56ab33dd6fb96b0f4c968b591b74 to encode to UTF-8, and now it seems to work fine with the password it failed on for me. For the benefit of @mikepound and others, I've come up with two test cases. Disclaimer: both of these are insecure and should not be used as passwords, especially not now that I've spoiled them on the internet.

At the time of writing, the first one gets me one occurrence and the second one gets me zero occurrences in the code as I've made it now. Previously, both versions would yield a `UnicodeEncodeError` and halt the script.

    $ echo "é" | python3 pwned.py
    $ echo "resumé" | python3 pwned.py

**Comment by mikepound** [comment]
I merged a couple of other PRs, could you look at where yours sits in relation to the code as of now?

**Comment by ToonSpin** [comment]
I fixed the merge conflicts:

- The UTF-8 issue in the comments of this PR was fixed in a PR you merged (issue #9). There was no meaningful difference there ("UTF-8" vs "utf-8"). I picked the other person's version.
- I removed a newline at the top of README.md, that gave another conflict, fixed that.

The rest of the differences, as of now, are that in this PR:

- Situations where passwords cannot be UTF-8 encoded are handled gracefully (as opposed to halting the program).
- There is always one line of output per password, making it easier to use with things such as `grep`.

**Comment by mikepound** [comment]
Great! Thanks a lot 👍

**Comment by ToonSpin** [comment]
The gratitude is mine! I enjoy your CF videos a lot and I too think Troy Hunt is doing good work. Glad to help.

**Pull request merged**
